export const COPY = Object.freeze({
  appTitle: '한화손보 AI 생체정보 기반 상품 추천',
  heroTitle: '얼굴 인식으로 내게 맞는 상품을 확인하세요',
  heroBody: '추정 나이와 성별을 확인하면 연령대와 성별에 맞는 한화손보 추천 상품을 보여드립니다.',
  privacyBullets: [
    '카메라는 버튼을 누른 뒤에만 켜집니다.',
    '필요하면 추정 결과를 직접 수정합니다.',
  ],
  startButton: '카메라로 나이·성별 추정',
  manualButton: '수동 입력으로 보기',
  retryButton: '다시 시도',
  resetButton: '처음으로',
  analyzeButton: '얼굴 입체 스캔 시작',
  stopScanButton: '얼굴 스캔 중지',
  stopCameraButton: '카메라 끄기',
  loadingModel: '분석 모델을 준비하고 있습니다',
  cameraReady: '얼굴을 찾으면 자동으로 스캔을 시작합니다.',
  analyzing: '얼굴 방향과 여러 각도의 프레임을 분석하고 있습니다...',
  estimateBadge: '추정 결과',
  productSourceLabel: '공식 출처 보기',
  fallbackTitle: '수동 입력으로 이어갑니다',
  fallbackBody: '카메라 권한 거부, 브라우저 제한, 얼굴 미검출, 낮은 신뢰도 상황에서는 수동 입력으로 상품 확인을 이어갑니다.',
});
