export const SOURCE_CHECKED_AT = '2026-06-07';

export const products = Object.freeze([
  {
    id: 'direct-driver',
    name: '캐롯 운전자보험',
    category: '운전자',
    summary: '운전 중 사고 이후 생길 수 있는 비용성 상황을 준비하는 운전자 상품입니다.',
    reasonTags: ['운전', '이동', '성인'],
    thumbnailIcon: '운전',
    thumbnailTone: 'blue',
    sourceUrl: 'https://www.carrotins.com/',
    sourceLabel: '한화손보 캐롯 공식 홈페이지',
    sourceCheckedAt: SOURCE_CHECKED_AT,
    caveat: '운전 여부와 직업, 차량 이용 형태에 따라 실제 확인해야 할 사항이 달라질 수 있습니다.',
  },
  {
    id: 'direct-cancer',
    name: '다이렉트 내가고른암보험',
    category: '암',
    summary: '암 및 유사암 진단비 등 주요 질병 보장을 중심으로 살펴보는 건강 상품입니다.',
    reasonTags: ['건강', '암', '성인'],
    thumbnailIcon: '암',
    thumbnailTone: 'purple',
    sourceUrl: 'https://mall.hwgeneralins.com/index.do',
    sourceLabel: '한화다이렉트 메인',
    sourceCheckedAt: SOURCE_CHECKED_AT,
    caveat: '질병 이력, 연령, 세부 담보 조건은 공식 자료로 별도 확인해야 합니다.',
  },
  {
    id: 'medical-indemnity',
    name: '한화실손의료보험(갱신형)',
    category: '실손',
    summary: '질병이나 상해로 실제 부담한 의료비를 중심으로 살펴보는 실손의료 상품입니다.',
    reasonTags: ['실손', '의료비', '건강'],
    thumbnailIcon: '실손',
    thumbnailTone: 'green',
    sourceUrl: 'https://www.hwgeneralins.com/upload/product/medical%282204%29_03.pdf',
    sourceLabel: '한화손보 실손의료보험 약관',
    sourceCheckedAt: SOURCE_CHECKED_AT,
    caveat: '실손의료보험은 갱신형 상품으로 보장내용, 자기부담금, 갱신 조건을 공식 자료에서 확인해야 합니다.',
  },
  {
    id: 'signature-women-health',
    name: '한화 시그니처 여성 건강보험 4.0(무)',
    category: '여성 건강',
    summary: '여성 질환과 여성암 관련 보장을 중심으로 구성된 여성 건강 상품입니다.',
    reasonTags: ['여성', '건강', '성인'],
    thumbnailIcon: '여성',
    thumbnailTone: 'pink',
    sourceUrl: 'https://www.carrotins.com/',
    sourceLabel: '한화손보 캐롯 공식 홈페이지',
    sourceCheckedAt: SOURCE_CHECKED_AT,
    caveat: '여성 전용 상품군이므로 본인이 원할 때만 공식 자료를 확인하세요.',
    genderSpecific: 'female',
  },
  {
    id: 'direct-fire',
    name: '다이렉트 119주택화재보험',
    category: '화재',
    summary: '거주 공간에서 생길 수 있는 화재·생활위험을 준비하는 주택화재 상품입니다.',
    reasonTags: ['주거', '생활', '가족'],
    thumbnailIcon: '화재',
    thumbnailTone: 'orange',
    sourceUrl: 'https://mall.hwgeneralins.com/index.do',
    sourceLabel: '한화다이렉트 메인',
    sourceCheckedAt: SOURCE_CHECKED_AT,
    caveat: '주택 형태, 소유/임차 여부, 담보 구성에 따라 확인할 내용이 달라집니다.',
  },
  {
    id: 'direct-dental',
    name: '치아안심보험',
    category: '치아',
    summary: '치과 치료와 구강 관리 관련 비용 부담을 살펴보는 치아 상품입니다.',
    reasonTags: ['치아', '건강', '생활'],
    thumbnailIcon: '치아',
    thumbnailTone: 'teal',
    sourceUrl: 'https://www.hwgeneralins.com/',
    sourceLabel: '한화손보 홈페이지',
    sourceCheckedAt: SOURCE_CHECKED_AT,
    caveat: '보장개시, 면책, 감액 등 세부 조건은 공식 상품 자료에서 확인해야 합니다.',
  },
  {
    id: 'direct-travel',
    name: '캐롯 해외여행보험',
    category: '여행',
    summary: '해외여행 중 생길 수 있는 의료·휴대품·일정 관련 변수를 준비하는 여행 상품입니다.',
    reasonTags: ['여행', '이동', '단기'],
    thumbnailIcon: '여행',
    thumbnailTone: 'sky',
    sourceUrl: 'https://www.carrotins.com/',
    sourceLabel: '한화손보 캐롯 공식 홈페이지',
    sourceCheckedAt: SOURCE_CHECKED_AT,
    caveat: '여행 일정, 목적지, 체류 기간에 따라 필요한 확인 사항이 달라질 수 있습니다.',
  },
  {
    id: 'comprehensive-health',
    name: '한화 더건강한 한아름종합보험(무)',
    category: '종합 건강',
    summary: '암·뇌·심장 등 여러 건강 위험을 함께 살펴볼 수 있는 종합 건강 상품입니다.',
    reasonTags: ['건강', '종합', '중장년'],
    thumbnailIcon: '건강',
    thumbnailTone: 'navy',
    sourceUrl: 'https://mall.hwgeneralins.com/ins/ltr/life_features_01.do',
    sourceLabel: '한화 더건강한 한아름종합보험 상품 페이지',
    sourceCheckedAt: SOURCE_CHECKED_AT,
    caveat: '세부 보장과 예시는 성별, 나이, 직업, 담보 구성에 따라 달라질 수 있습니다.',
  },
  {
    id: 'senior-care',
    name: '한화 더 경증 간편건강보험Ⅱ(세만기형)(무)',
    category: '간병/노후',
    summary: '간병인 사용 입원생활비 등 노후 간병비 부담을 중심으로 살펴보는 간병인 상품입니다.',
    reasonTags: ['간병', '노후', '건강'],
    thumbnailIcon: '간병',
    thumbnailTone: 'gold',
    sourceUrl: 'https://mall.hwgeneralins.com/ins/ltr/care_features_01.do',
    sourceLabel: '한화손보 간병인보험 상품 페이지',
    sourceCheckedAt: SOURCE_CHECKED_AT,
    caveat: '간병 관련 담보, 고지유형, 연령 조건, 갱신 여부는 공식 자료에서 확인해야 합니다.',
  },
  {
    id: 'direct-golf',
    name: '다이렉트 홀인원보험',
    category: '골프',
    summary: '골프 활동 중 발생할 수 있는 비용성 상황을 준비하는 골프 상품입니다.',
    reasonTags: ['골프', '취미', '활동'],
    thumbnailIcon: '골프',
    thumbnailTone: 'green',
    sourceUrl: 'https://www.carrotins.com/product/holeinone/intro',
    sourceLabel: '한화손보 캐롯 홀인원보험 페이지',
    sourceCheckedAt: SOURCE_CHECKED_AT,
    caveat: '취미·운동 활동 여부에 따라 확인할 내용이 달라질 수 있습니다.',
  },
]);

export function getProductById(id) {
  return products.find((product) => product.id === id);
}
